name: Build Image

on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: node image build
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./
        file: ./Dockerfile
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push: true
        provenance: false
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/erikjiang/systemd-node:${{ github.sha }}
          ghcr.io/erikjiang/systemd-node:latest
        build-args: ""
        cache-from: type=gha
        cache-to: type=gha,mode=max